{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tg-api.secretName" . }}
  labels:
    {{- include "tg-api.labels" . | nindent 4 }}
type: Opaque
data:
  apiId: {{ .Values.secret.apiId | default "" | b64enc }}
  apiHash: {{ .Values.secret.apiHash | default "" | b64enc }}
{{- end }}

