version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=me@mamad.dev"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--accesslog=true"
      - "--accesslog.fields.headers.names.User-Agent=keep"
      - "--accesslog.fields.headers.names.Authorization=redact"
      - "--accesslog.fields.headers.names.Content-Type=keep"
      - "--accesslog.fields.headers.names.X-Forwarded-For=keep"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.token-filter.replacepathregex.regex=^(/bot\\d+):[-\\w]+/(.*)$$"
      - "traefik.http.middlewares.token-filter.replacepathregex.replacement=/$$1:<hidden-token>/$$2"

  api:
    image: ghcr.io/reloadlife/tg-api:prod
    restart: always
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    deploy:
      mode: replicated
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${HOSTNAME}`) && PathPrefix(`/`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.services.api.loadbalancer.server.port=8081"
      - "traefik.http.routers.api.middlewares=token-filter@docker"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/file"
      - "traefik.http.routers.api-files.rule=Host(`${HOSTNAME}`) && PathPrefix(`/file`)"
      - "traefik.http.routers.api-files.entrypoints=websecure"
      - "traefik.http.routers.api-files.tls=true"
      - "traefik.http.routers.api-files.tls.certresolver=myresolver"
      - "traefik.http.routers.api-files.middlewares=api-strip@docker"
      - "traefik.http.routers.api-files.service=api-files"
      - "traefik.http.services.api-files.loadbalancer.server.port=8081"

volumes:
  letsencrypt:
  telegram-bot-api-data:
